[package]
name = "config"
version = "0.2.0"
edition = "2024"
license.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
serde_with.workspace = true
toml_edit.workspace = true

[dev-dependencies]
proptest.workspace = true
tempfile.workspace = true
