[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
thiserror.workspace = true
toml = "0.8.19"
tracing.workspace = true

[lints]
workspace = true

[dev-dependencies]
tempfile = "3.12.0"
